### ISSUE TITLE
اپدیت کتاب

### ISSUE THREAD

**Issue by abbasgholia** [dutymess/laravel-0-to-60#10]
بیش از دو ساله هنوز کتاب اپدیت نشده چرا اخه؟

**Comment by dutymess** [comment]
حق با شماست. متأسفانه مشغله روزانه و دغدغه‌های زندگی اجازه نداد اون طور که برنامه داشتم و دوست داشتم، به صورت منظم روی این کتاب کار کنم. با این حال برنامه‌ای چیدم که اگر به‌خوبی پیش بره می‌تونم به‌زودی کار رو از سر بگیرم.
از توجه شما سپاسگزارم.
