### ISSUE TITLE
عالی

### ISSUE THREAD

**Issue by hadidadkhah** [dutymess/laravel-0-to-60#4]
<div dir="rtl" lang="fa">
سلام و خسته نباشید. خیلی عالی و کاربردی.
من که مرتب این صفحه را چک می‌کنم و منتظر درس‌های جدیدتان هستم.
بی هیچ حرف اضافه و بدون رها کردن نکات مهم همه چیز را پوشش می‌دهید.
امروز موقع خواندن آخرین درس در یکی از عکس‌ها متوجه شدم و برایم سوال شد. شاید دلیلی برای این اسم دارید. 
</div>
<span dir="ltr">apollo.sexy?!</span>

**Comment by dutymess** [comment]
<div dir="rtl" lang="fa">
ممنونم از توجهت و حمایتت. 
من از والت که محصول دیگه‌ای از خالق لاراول هست برای سرو لوکال سایت‌هام استفاده می‌کنم. 
 پسوندی که برای سایت‌های سروشدهٔ لوکال خودم انتخاب کرده بودم
`dev`
بود که مدتی پیش توسط گوگل تصرف شد و اگر بدون پروتکل امن باز می‌شد خطا می‌داد. برای حل این مشکل سراغ اسم دامنه‌ای رفتم که هم در عالم خارج وجود داشته باشه و مرورگرم دنبال سرچ کردن نباشه، و هم خیالم راحت باشه که سایت واقعی‌ای نیست که بخوام با اون دامنه بهش سر بزنم. چی بهتر از این کلمه؟ هم فانه و هم تماشا :)
</div>


👓  [Laravel Valet: https://laravel.com/docs/5.6/valet](https://laravel.com/docs/5.6/valet)
