### ISSUE TITLE
Specified key was too long

### ISSUE THREAD

**Issue by zahraghaffarpour** [dutymess/laravel-0-to-60#7]
<div dir="rtl" lang="fa">
سلام من طبق آموزش کتاب جلو رفتم و مایگریشن های users و missions رو ایجاد کردم.
با اجرای دستور:
php artisan migrate
با این ارور مواجه شدم:

Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes")       C:\wamp\www\Apollo\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458

که باعث میشد جدول ها در دیتابیس ایجاد نشوند.
در نهایت با بررسی که کردم متوجه شدم مشکل  در این قسمت از فایل مایگریشن users است:
$table->index(['last_name' , 'first_name'] , 'users_name_index');
چون طول کاراکترهای firstname و lastname تعیین نشده طول کاراکترهاشون خیلی طولانی میشد و ارور میداد  با تغییر این قسمت تونستم این ارور رو برطرف کنم که اول عدد 255 رو دادم حل نشد ولی در نهایت با تعیین 45 کاراکتر برای هر کدام از ستون ها مشکل رفع شد:
$table->string('first_name',45)->after('id');
$table->string('last_name',45)->after('first_name');

بنده باین روش حل کردم به نظرم صلاح دونستم که باهاتون مطرح کنم تا اگه نیازه تو کتابتون اصلاح کنید یا اگر روش بهتری پیشنهاد میدید خوشحال میشم ارائه بدید.

در ضمن ورژن لاراول که کار میکنم 5.6 هست و ورژن پی اچ پی 
7.1
باتشکر
   </div>

**Comment by dutymess** [comment]
<div dir="rtl" lang="fa">
سلام. ممنونم از توجهتون. مشکلی که دارید به احتمال زیاد ناشی از نسخه 
mySql
در سیستم عاملی که استفاده می‌کنید هست. کاش ذکر می‌کردید که از چه سیستمی استفاده می‌کنید، ولی من حدس می‌زنم ویندوز باشه.

به فایل `app/Providers/AppServiceProvider` برید و این خط رو در متد بوت اضافه کنید.
</div>

```php
Schema::defaultStringLength(120);
```

<div dir="rtl" lang="fa">
یادتون نره که نیم‌اسپیس مورد نظر در بالای فایل اضافه شده باشه.
</div>

```php
use Illuminate\Support\Facades\Schema;
```

<div dir="rtl" lang="fa">
این کار قاعدتا مشکل رو حل می‌کنه. ما عدد ۱۲۰ رو روی بیشتر سیستم‌ها آزمایش کردیم و مشکلی نبوده ولی اگر برای شما مشکلی هست، می‌تونید کمتر کنید.

ممنون می‌شم اگر حل شدن یا نشدن مشکل رو به من خبر بدید.
</div>

**Comment by zahraghaffarpour** [comment]
<div dir="rtl" lang="fa">
درسته سیستم عاملم ویندوز هست و نسخه mysql  5.7.21 هست خیلی ممنونم بابت راه حللتون امتحان کردم حل شد
  </div>
