### ISSUE TITLE
درج و حذف 100 رکورد تصادفی

### ISSUE THREAD

**Issue by misagh01** [dutymess/laravel-0-to-60#8]
<div dir="rtl" lang="fa">
  سلام
در مورد پاسخ نمونه شما به تمرین درج و حذف صد 
رکورد،  سوالی داشتم، 

https://github.com/dutymess/apollo-0-to-60/blob/chapter-04-lesson-02/app/Http/Controllers/Practices/CreateAndDeleteRandomRecordsController.php

اگر اپلیکیشن ما کاربر دیگری هم داشته باشد و در حین درج رکوردها توسط ما، رکوردهایی در همان جدول درج کند در اینصورت هنگام حذف رکوردها،  رکوردهای کاربر دوم هم حذف میشود
اصلا چنین اتفاقی امکان دارد و راه حلش چیست؟ 
</div>

**Comment by dutymess** [comment]
<div dir="rtl" lang="fa">
سلام از توجه شما سپاسگزارم.


پاسخ مثبت است. در مساله ساده و عجیب و غریب ما، اگر کاربر همزمان دیگری هم از برنامه استفاده کند، ممکن است رکوردهای دیگری را نیز همراه با رکوردهای خود پاک کند.

چنین اتفاقی در عالم واقعی نمی‌افتد، چرا که مسأله‌ها به این سادگی و عجیبی نیستند. اما اگر بخواهیم همین وضع را کمی اصلاح کنیم، طوری که کاربران فقط رکوردهای خودشان را پاک کنند، می‌بایست به جای آن که فقط شناسه اول و آخر را به خاطر بسپاریم، تک‌تک شناسه‌هایی که اضافه می‌کنیم را در حافظه نگاه داریم و سپس همان‌ها را حذف کنیم.
</div>

**Comment by misagh01** [comment]
<div dir="rtl" lang="fa">
بله متوجه شدم، ممنون از پاسخ شما
</div>
